# Generated by Django 6.0.6 on 2026-06-22 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_creators_bio_creators_category_creators_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creators',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creators',
            name='sub_fans',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='creators',
            name='sub_super_fans',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='creators',
            name='sub_supporters',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
