# Generated by Django 6.0.6 on 2026-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_creators_img_alter_creators_sub_fans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creators',
            name='subscribers',
            field=models.JSONField(default=list, null=True),
        ),
    ]
