# Generated by Django 6.0.6 on 2026-06-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_creators_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creators',
            name='subscribers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
