# Generated by Django 6.0.6 on 2026-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_creators_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creators',
            name='post_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
