import os
import cloudinary.uploader
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.parsers import MultiPartParser, FormParser
from accounts.models import CREATORS  # Replace with your actual model name

class CreatorRegistrationView(APIView):
    # CRITICAL: MultiPartParser allows Django to parse files and text data together
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request):
        # 1. Extract regular text data sent from the frontend
        username = request.data.get('username')
        display_name = request.data.get('display_name', '')
        bio = request.data.get('bio', '')
        sub_fans = request.data.get('sub_fans', 0)
        category = request.data.get('category', '')
        sub_supporters = request.data.get('sub_supporters', 0)
        sub_fans = request.data.get('sub_fans', 0)
        sub_super_fans = request.data.get('sub_super_fans', 0)
        subscribers = request.data.get('subscribers', [])
        # 2. Extract the raw file object
        img = request.FILES.get('img')

        # Basic Validation
        if not username or not img:
            return Response(
                {"error": "Name and profile picture are required fields."}, 
                status=status.HTTP_400_BAD_REQUEST
            )

        try:
            # 3. Fire the image file off to the Cloudinary servers
            upload_result = cloudinary.uploader.upload(
                img,
                folder="creators_profiles/"
            )
            
            # 4. Grab the permanent secure CDN string URL generated by Cloudinary
            cloud_image_url = upload_result.get("secure_url")

            # 5. Save EVERYTHING to your database model at the same time
            new_creator = CREATORS.objects.create(
                username=username,
                display_name=display_name,
                bio=bio,
                category=category,
                sub_supporters=int(sub_supporters),
                sub_super_fans=int(sub_super_fans),
                sub_fans=int(sub_fans),
                img=cloud_image_url  # Storing the string link in your MySQL column
            )

            return Response({
                "message": "Creator profile created successfully!",
                "data": {
                    "id": new_creator.id,
                    "username": new_creator.username,
                    "img": new_creator.img # The React app can use this to render <img> tags
                }
            }, status=status.HTTP_201_CREATED)

        except Exception as e:
            return Response(
                {"error": f"Registration failed: {str(e)}"}, 
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )